

runtime: nodejs20  # Specify the runtime environment

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: \1
    upload: .*

  # Catch all handler to serve index.html
  - url: /.*
    static_files: index.html
    upload: index.html